### ISSUE TITLE
English page not showing add questions for admin

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#79]
When admin logs in , the add question link on navbar is not visible . It should be available at all pages . Content at the navbar should not change

**Comment by ShivaRapolu01** [comment]
I would like to work on this

**Comment by mohit200008** [comment]
I have assigned one issue to you @ShivaRapolu01

**Comment by shmiitg** [comment]
It is showing @mohit200008 on the english page. I worked on this issue admin access to question form issue and made the changes in the navbar
![Screenshot (349)_LI](https://user-images.githubusercontent.com/70333141/147591136-c32a791e-fa65-49d9-81f6-c1bf09404aca.jpg)
It will be hidden only when user is logged in

**Comment by shmiitg** [comment]
![Screenshot (350)](https://user-images.githubusercontent.com/70333141/147591308-ba7b102f-9c87-44a2-b441-97f59d7fcffa.png)
When normal user logs in, it will be hidden

**Comment by mohit200008** [comment]
add my name

**Comment by mohit200008** [comment]
![Capture](https://user-images.githubusercontent.com/56565813/147603870-5a324399-be0e-4a10-9643-e03572a61756.PNG)
@shmiitg  i added this user as admin, its showing add question on the hindi page

**Comment by shmiitg** [comment]
Actually the hindi page is not linked with the auth.js file. You have created a random document but its id should match with the original user id
![Screenshot (351)_LI](https://user-images.githubusercontent.com/70333141/147604547-2cfcc7d1-c65a-4561-8109-cb872f1c9f63.jpg)
![Screenshot (352)_LI](https://user-images.githubusercontent.com/70333141/147604595-a3569a0d-e36a-4bb7-b623-fb2c5752b44f.jpg)
Both of these ids should match which is I am using in the code to find the user.
You can check for the rest of the users its matching.
Actually the hindi page has some issues and I just saw that the logout button of hindi page doesn't work and user creds are also not shown because the auth.js file is not linked with it. I will raise this issue and correct these things. 
As you see the user credentials are not shown and logout button only redirects to signup form instead of actually logging out.
![Screenshot (353)](https://user-images.githubusercontent.com/70333141/147604747-35e30421-0e0b-4409-9e6e-12001c00a58b.png)

**Comment by shmiitg** [comment]
Actually it was mine fault. I forgot to add a class to the hindi page because of which is auth.js file was not working in hindi page. I corrected that and making a pr now.
